- name: Deploy Application
  hosts: all
  serial: 10
  remote_user: root
  tasks:
    - name: upload file
      template:
        src: dist.zip
        dest: test/
        owner: ec2-user
        group: ec2-user
        mode: 0777
